#################################################################
## Home Assistant
#################################################################

homeassistant:
  name: Home
  latitude: REDACTED
  longitude: REDACTED
  elevation: REDACTED
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

frontend:
updater:
  reporting: no
sun:
conversation:
discovery:
  ignore:
    - apple_tv
config:

http:
  api_password: REDACTED
  ssl_certificate: /etc/letsencrypt/live/REDACTED/REDACTED
  ssl_key: /etc/letsencrypt/live/REDACTED/REDACTED
  base_url: REDACTED
  trusted_networks:
    - 127.0.0.1
    - REDACTED.0/24
    - REDACTED.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5

#################################################################
## Components
#################################################################

ecobee:
  api_key: REDACTED
  hold_temp: true

light:
  platform: hue
  host: REDACTED.106
  allow_hue_groups: false
  allow_unreachable: true

emulated_hue:
  host_ip: REDACTED.105
  listen_port: 8300
  type: alexa
  upnp_bind_multicast: false
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: false

media_player:
  - platform: plex
  - platform: apple_tv
    host: REDACTED.150
    login_id: REDACTED
    name: Living Room Apple TV
  - platform: apple_tv
    host: REDACTED.151
    login_id: REDACTED
    name: USER1's Office Apple TV
  - platform: apple_tv
    host: REDACTED.152
    login_id: REDACTED
    name: Bedroom Apple TV
  - platform: sonos
    hosts:
      - REDACTED.200
      - REDACTED.201
      - REDACTED.202
      - REDACTED.203
      - REDACTED.204
      - REDACTED.205
      - REDACTED.206
      - REDACTED.208

remote:
  - platform: harmony
    name: Media Center
    host: REDACTED.109

ios:

wemo:
  static:
    - REDACTED.111

ifttt:
  key: REDACTED

device_tracker:
  - platform: asuswrt
    host: REDACTED.1
    username: REDACTED
    password: REDACTED
    protocol: telnet
    track_new_devices: no
    interval_seconds: 12
    consider_home: 180
  - platform: locative

cover:
  platform: myq
  name: Garage Door
  username: REDACTED
  password: REDACTED
  type: chamberlain

ring:
    username: REDACTED
    password: REDACTED

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion

camera:
  - platform: foscam
    ip: REDACTED.107
    name: Garage Camera
    port: REDACTED
    username: REDACTED
    password: REDACTED
  - platform: ffmpeg
    input: http://REDACTED/rtplive/REDACTED/playlist.m3u8
    name: REDACTED
    extra_arguments: '-headers "X-ForREDACTEDed-For: REDACTED"'

tts:
  - platform: google

google:
  client_id: REDACTED
  client_secret: REDACTED
  track_new_calendar: false

wink:
  email: REDACTED
  password: REDACTED
  client_id: REDACTED
  client_secret: REDACTED

#################################################################
## Includes
#################################################################

automation: !include_dir_merge_list automation
recorder: !include recorder.yaml
logbook: !include logbook.yaml
history: !include history.yaml
zone: !include zones.yaml
group: !include groups.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
script: !include scripts.yaml
weblink: !include weblinks.yaml
