#################################################################
## Media Player Automations
#################################################################

        ##########################################################
        ## Plex Lights On
        ##########################################################

- alias: Media - Plex Stopped Lights On

  trigger:
    - platform: state
      entity_id: media_player.living_room
      from: 'playing'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: group.living_room_lights
      data:
       transition: 3
       profile: relax
    - service: light.turn_on
      entity_id: light.hallway_light
      data:
       brightness: 25
    - service: light.turn_on
      entity_id:
        - light.dining_room_table
        - light.bathroom_vanity
        - light.kitchen_sink
      data:
       brightness: 100
    - service: light.turn_on
      entity_id: light.kitchen_cabinets
      data:
       brightness: 2

        ##########################################################
        ## Plex Lights Off
        ##########################################################

- alias: Media - Plex Started Lights Off

  trigger:
    - platform: state
      entity_id: media_player.living_room
      to: 'playing'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'

  action:
    - service: light.turn_off
      entity_id:
        - group.living_room_lights
        - light.hallway_light
      data:
       transition: 5
    - service: light.turn_off
      entity_id:
        - group.dining_room
        - group.kitchen
        - light.bathroom_vanity
    - service: homeassistant.turn_on
      entity_id: input_boolean.watching_plex

        ##########################################################
        ## Turn Off Watching Plex Boolean
        ##########################################################

- alias: Media - Turn Off Watching Plex Boolean

  trigger:
    - platform: state
      entity_id: media_player.living_room
      state: 'idle'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.watching_plex

        ##########################################################
        ## Late Night TV Watching before Midnight Lights On
        ##########################################################

- alias: Media - Late Night TV Watching Lights On before Midnight

  trigger:
    - platform: state
      entity_id: media_player.living_room_apple_tv
      to: 'paused'
      for:
        hours: 0
        minutes: 0
        seconds: 5

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: time
      after: '21:30'
    - condition: state
      entity_id: group.friends_and_family
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.watching_plex
      state: 'off'
    - condition: state
      entity_id: input_select.remote
      state: 'Watch TV'

  action:
    - service: light.turn_on
      entity_id: group.living_room_lights
      data:
       transition: 1
       profile: relax
       brightness: 25
    - service: light.turn_on
      entity_id: light.hallway_light
      data:
       transition: 1
       profile: relax
       brightness: 3
    - service: light.turn_on
      entity_id:
        - light.dining_room_table
        - light.bathroom_vanity
        - light.kitchen_sink
        - light.kitchen_cabinets
      data:
       brightness: 2

        ##########################################################
        ## Late Night TV Watching after Midnight Lights On
        ##########################################################

- alias: Media - Late Night TV Watching Lights On after Midnight

  trigger:
    - platform: state
      entity_id: media_player.living_room_apple_tv
      to: 'paused'
      for:
        hours: 0
        minutes: 0
        seconds: 5

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: time
      after: '00:00'
      before: '03:00'
    - condition: state
      entity_id: group.friends_and_family
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.watching_plex
      state: 'off'
    - condition: state
      entity_id: input_select.remote
      state: 'Watch TV'

  action:
    - service: light.turn_on
      entity_id: group.living_room_lights
      data:
       transition: 1
       profile: relax
       brightness: 25
    - service: light.turn_on
      entity_id: light.hallway_light
      data:
       transition: 1
       profile: relax
       brightness: 3
    - service: light.turn_on
      entity_id:
        - light.dining_room_table
        - light.bathroom_vanity
        - light.kitchen_sink
        - light.kitchen_cabinets
      data:
       brightness: 2

        ##########################################################
        ## Late Night TV Watching after Midnight Lights Off
        ##########################################################

- alias: Media - Late Night TV Watching Lights Off after Midnight

  trigger:
    - platform: state
      entity_id: media_player.living_room_apple_tv
      to: 'playing'
      for:
        hours: 0
        minutes: 0
        seconds: 10

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: time
      after: '00:00'
      before: '03:00'
    - condition: state
      entity_id: group.friends_and_family
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.watching_plex
      state: 'off'
    - condition: state
      entity_id: input_select.remote
      state: 'Watch TV'

  action:
    - service: light.turn_off
      entity_id:
        - group.living_room_lights
        - light.hallway_light
      data:
       transition: 1
    - service: light.turn_off
      entity_id:
        - group.dining_room
        - group.kitchen
        - light.bathroom_vanity

        ##########################################################
        ## Late Night TV Watching before Midnight Lights Off
        ##########################################################

- alias: Media - Late Night TV Watching Lights Off before Midnight

  trigger:
    - platform: state
      entity_id: media_player.living_room_apple_tv
      to: 'playing'
      for:
        hours: 0
        minutes: 0
        seconds: 10

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: time
      after: '21:30'
    - condition: state
      entity_id: input_boolean.watching_plex
      state: 'off'
    - condition: state
      entity_id: input_select.remote
      state: 'Watch TV'

  action:
    - service: light.turn_off
      entity_id:
        - group.living_room_lights
        - light.hallway_light
      data:
       transition: 1
    - service: light.turn_off
      entity_id:
        - group.dining_room
        - group.kitchen
        - light.bathroom_vanity

      #################################################################
      ## Remote
      #################################################################

- alias: Media - Remote external update Media Center

  trigger:
    - platform: state
      entity_id: remote.media_center

  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.remote
        option: >
          {{ states.remote.media_center.attributes.current_activity }}

- alias: Media - Remote start activity from input select media center

  trigger:
    - platform: state
      entity_id: input_select.remote

  action:
    - service: script.turn_on
      entity_id: script.input_select_harmony

      #################################################################
      ## Sonos
      #################################################################

- alias: Media - Ungroup Sonos Every Morning

  trigger:
    - platform: time
      after: '06:00'

  action:
    - service: media_player.sonos_unjoin
      entity_id:
        - media_player.media_center
        - media_player.living_room_sp
        - media_player.dining_room
        - media_player.kitchen
        - media_player.bathroom
        - media_player.USER1s_office
        - media_player.USER2s_office
        - media_player.basement
