#################################################################
## Thermostat Automations
#################################################################

        ##########################################################
        ## Set Thermostat Home
        ##########################################################

- alias: Thermostat - Home

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.thermostat_away
#     re-enable Summer or Winter Mode
    - service: homeassistant.turn_on
      entity_id: group.summer_mode
#    - service: homeassistant.turn_on
#      entity_id: group.winter_mode

        ##########################################################
        ## Set Thermostat Away
        ##########################################################

- alias: Thermostat - Away

  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.thermostat_away
    - service: homeassistant.turn_off
      entity_id: group.summer_mode
    - service: homeassistant.turn_off
      entity_id: group.winter_mode
    - service: climate.set_operation_mode
      data:
        entity_id: climate.window_unit
        operation_mode: off

        ##########################################################
        ## Set Thermostat Home When USER2 Leaves Work
        ##########################################################

- alias: Thermostat - Set Home When USER2 Leaves Work

  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'work'
      to: 'not_home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: device_tracker.USER1DEVICE
      state: 'not_home'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.thermostat_away

        ##########################################################
        ## Turn Thermostat on Summer
        ##########################################################

- alias: Thermostat - Turn on Summer

  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_temperature
      above: 75

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.thermostat_away

        ##########################################################
        ## Turn Thermostat off Summer
        ##########################################################

- alias: Thermostat - Turn off Summer

  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_temperature
      below: 74

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.thermostat_away

        ##########################################################
        ## Turn Thermostat on Winter
        ##########################################################

- alias: Thermostat - Turn on Winter

  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_temperature
      below: 65

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.thermostat_away

        ##########################################################
        ## Turn Thermostat off Winter
        ##########################################################

- alias: Thermostat - Turn off Winter

  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_temperature
      above: 66

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.thermostat_away

        ##########################################################
        ## Disable Summer / Winter Mode on Start
        ##########################################################

- alias: Thermostat - Disable Summer or Winter Mode on Start

  trigger:
    - platform: homeassistant
      event: start

  action:
#     Disable Summer or Winter Mode
#    - service: homeassistant.turn_off
#      entity_id: group.summer_mode
    - service: homeassistant.turn_off
      entity_id: group.winter_mode

        ##########################################################
        ## Turn off Thermostat when Door Opens for Extended Period
        ##########################################################

- alias: Thermostat - Turn off when Door Opens for Extended Period

  trigger:
    - platform: state
      entity_id: group.doors
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: group.summer_mode
      state: 'on'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.thermostat_away

        ##########################################################
        ## Thermostat on Demand Home
        ##########################################################

- alias: Thermostat - On Demand Home

  trigger:
    - platform: state
      entity_id: input_boolean.thermostat_away
      from: 'on'
      to: 'off'

  action:
    - service: climate.set_hold_mode
      data:
        entity_id: climate.main_floor
        hold_mode: None

        ##########################################################
        ## Thermostat on Demand Away
        ##########################################################

- alias: Thermostat - On Demand Away

  trigger:
    - platform: state
      entity_id: input_boolean.thermostat_away
      from: 'off'
      to: 'on'

  action:
    - service: climate.set_away_mode
      data:
        entity_id: climate.main_floor
        away_mode: true

        ##########################################################
        ## Turn on Window Unit at 10a
        ##########################################################

- alias: Thermostat - Turn on Window Unit at 10a

  trigger:
    - platform: time
      after: '10:00'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: group.summer_mode
      state: 'on'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.window_unit
        operation_mode: 'eco'
    - service: climate.fan_mode
      data:
        entity_id: climate.window_unit
        fan_mode: 'high'
    - service: climate.set_temperature
      data:
        entity_id: climate.window_unit
        temperature: '68'
    - service: switch.turn_on
      entity_id: switch.hallway_fan

        ##########################################################
        ## Turn off Window Unit at 9p
        ##########################################################

- alias: Thermostat - Turn off Window Unit at 9p

  trigger:
    - platform: time
      after: '21:00'

  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.window_unit
        operation_mode: 'off'
    - service: switch.turn_off
      entity_id: switch.hallway_fan

        ##########################################################
        ## Turn on Window Unit when Office is Hot
        ##########################################################

- alias: Thermostat - Turn on Window Unit when Office is Hot

  trigger:
    - platform: numeric_state
      entity_id: sensor.office_temperature
      above: 86

  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.summer_mode
        state: 'on'
      - condition: state
        entity_id: group.household
        state: 'not_home'

  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.window_unit
        operation_mode: 'eco'
    - service: climate.fan_mode
      data:
        entity_id: climate.window_unit
        fan_mode: 'high'
    - service: climate.set_temperature
      data:
        entity_id: climate.window_unit
        temperature: '68'
    - service: switch.turn_on
      entity_id: switch.hallway_fan
    - service: notify.ios_USER1s_iphone
      data:
        message: Office is Hot Turning on Window Unit

        ##########################################################
        ## Turn on Window Unit when Hot Outside
        ##########################################################

- alias: Thermostat - Turn on Window Unit when Hot Outside

  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_temperature
      above: 80

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: group.summer_mode
      state: 'on'
    - condition: time
      after: '10:00'
      before: '21:00'

  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.window_unit
        operation_mode: 'eco'
    - service: climate.fan_mode
      data:
        entity_id: climate.window_unit
        fan_mode: 'high'
    - service: climate.set_temperature
      data:
        entity_id: climate.window_unit
        temperature: '68'
    - service: switch.turn_on
      entity_id: switch.hallway_fan

        ##########################################################
        ## Turn off Winodw Unit When below 80 Outside and Away
        ##########################################################

- alias: Thermostat - Turn off Winodw Unit When below 80 Outside and Away

  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_temperature
      below: 80

  condition:
    - condition: state
      entity_id: group.household
      state: 'not_home'

  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.window_unit
        operation_mode: 'off'
    - service: switch.turn_off
      entity_id: switch.hallway_fan

        ##########################################################
        ## Turn off Winodw Unit When below 68 Outside
        ##########################################################

- alias: Thermostat - Turn off Winodw Unit When below 68 Outside

  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_temperature
      below: 68

  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.window_unit
        operation_mode: 'off'
    - service: switch.turn_off
      entity_id: switch.hallway_fan

        ##########################################################
        ## Adjust Thermostat for Overnight Guests before Midnight
        ##########################################################

- alias: Thermostat - Turn on Guest Settings before Midnight

  trigger:
    - platform: state
      entity_id: input_boolean.guest_mode
      state: 'on'

  condition:
    - condition: time
      after: '23:31'
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: climate.set_hold_mode
      data:
        entity_id: climate.main_floor
        #Guest = smart3
        hold_mode: "smart3"

        ##########################################################
        ## Turn on Window Unit When Guests Staying before Midnight
        ##########################################################

- alias: Thermostat - Turn on Window Unit When Guests Staying before Midnight

  trigger:
    - platform: state
      entity_id: input_boolean.guest_mode
      state: 'on'

  condition:
    - condition: time
      after: '23:31'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: group.summer_mode
      state: 'on'

  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.window_unit
        operation_mode: 'eco'
    - service: climate.fan_mode
      data:
        entity_id: climate.window_unit
        fan_mode: 'high'
    - service: climate.set_temperature
      data:
        entity_id: climate.window_unit
        temperature: '68'
    - service: switch.turn_on
      entity_id: switch.hallway_fan

        ##########################################################
        ## Adjust Thermostat for Overnight Guests after Midnight
        ##########################################################

- alias: Thermostat - Turn on Guest Settings after Midnight

  trigger:
    - platform: state
      entity_id: input_boolean.guest_mode
      state: 'on'

  condition:
    - condition: time
      after: '00:00'
      before: '04:59'
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: climate.set_hold_mode
      data:
        entity_id: climate.main_floor
        #Guest = smart3
        hold_mode: "smart3"

        ##########################################################
        ## Turn on Window Unit When Guests Staying after Midnight
        ##########################################################

- alias: Thermostat - Turn on Window Unit When Guests Staying after Midnight

  trigger:
    - platform: state
      entity_id: input_boolean.guest_mode
      state: 'on'

  condition:
    - condition: time
      after: '00:00'
      before: '04:59'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: group.summer_mode
      state: 'on'

  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.window_unit
        operation_mode: 'eco'
    - service: climate.fan_mode
      data:
        entity_id: climate.window_unit
        fan_mode: 'high'
    - service: climate.set_temperature
      data:
        entity_id: climate.window_unit
        temperature: '68'
    - service: switch.turn_on
      entity_id: switch.hallway_fan

        ##########################################################
        ## If USER1 is not Home Override WFH Mode
        ##########################################################

- alias: Thermostat - Override WFH Mode

  trigger:
    - platform: time
      after: '10:01'

  condition:
    - condition: state
      entity_id: input_boolean.thermostat_away
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: device_tracker.USER1DEVICE
      state: 'not_home'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: climate.set_hold_mode
      data:
        entity_id: climate.main_floor
        hold_mode: "home"

        ##########################################################
        ## Set Thermostat Home if USER2 Working at 5a
        ##########################################################

- alias: Thermostat - Set Thermostat Home if USER2 Working at 5a

  trigger:
    - platform: time
      after: '05:00'

  condition:
    - condition: state
      entity_id: input_boolean.thermostat_away
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.USER2_working
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: device_tracker.USER2DEVICE
      state: 'home'

  action:
    - service: climate.set_hold_mode
      data:
        entity_id: climate.main_floor
        hold_mode: "home"

        ##########################################################
        ## Reset Thermostat when USER2 Leaves
        ##########################################################

- alias: Thermostat - Reset Thermostat when USER2 Leaves

  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'home'
      to: 'not_home'

  condition:
    - condition: time
      after: '05:00'
      before: '07:00'
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: input_boolean.thermostat_away
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER2_working
      state: 'on'

  action:
    - service: climate.set_hold_mode
      data:
        entity_id: climate.main_floor
        hold_mode: None
